spring:
  mail:
    host: smtp.163.com
    username: 13607563956@163.com
    password: HPbGKpbzSQ6XMVTH
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    default-encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/BookManager
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 86400
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    web: debug
server:
  port: 8080